# ⚠️ DO NOT EDIT! GENERATED VIA openapi-generator ⚠️

openapi: 3.0.2
info:
  title: openTDF
  license:
    name: MIT
  version: 1.0.0
  x-logo:
    url: https://inxmad4bw31barrx17wec71c-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/o_efa1e48d0db5ebc8-4.png
paths:
  /attributes:
    get:
      tags:
        - Attributes
      summary: Read Attributes
      operationId: read_attributes_attributes_get
      parameters:
        - required: false
          schema:
            title: Authority
            maxLength: 2000
            minLength: 1
            type: string
            format: uri
          name: authority
          in: query
        - required: false
          schema:
            title: Name
            type: string
          name: name
          in: query
        - required: false
          schema:
            title: Rule
            type: string
          name: rule
          in: query
        - required: false
          schema:
            title: Order
            type: string
          name: order
          in: query
        - required: false
          schema:
            title: Sort
            pattern: ^(-*((state)|(rule)|(name)|(values)),)*-*((state)|(rule)|(name)|(values))$
            type: string
            default: ""
          name: sort
          in: query
        - required: false
          schema:
            title: Offset
            minimum: 1.0
            type: integer
            default: 1
          name: offset
          in: query
        - required: false
          schema:
            title: Limit
            maximum: 1000.0
            minimum: 1.0
            type: integer
            default: 100
          name: limit
          in: query
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Read Attributes Attributes Get
                type: array
                items:
                  maxLength: 65536
                  minLength: 1
                  type: string
                  format: uri
              example:
                - https://opentdf.io/attr/IntellectualProperty/value/TradeSecret
                - https://opentdf.io/attr/ClassificationUS/value/Unclassified
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
  /definitions/attributes:
    get:
      tags:
        - Attributes Definitions
      summary: Read Attributes Definitions
      operationId: read_attributes_definitions_definitions_attributes_get
      parameters:
        - required: false
          schema:
            title: Authority
            maxLength: 2000
            minLength: 1
            type: string
            format: uri
          name: authority
          in: query
        - required: false
          schema:
            title: Name
            type: string
          name: name
          in: query
        - required: false
          schema:
            title: Order
            type: string
          name: order
          in: query
        - required: false
          schema:
            title: Sort
            pattern: ^(-*((id)|(state)|(rule)|(name)|(values)),)*-*((id)|(state)|(rule)|(name)|(values))$
            type: string
            default: ""
          name: sort
          in: query
        - required: false
          schema:
            title: Offset
            minimum: 1.0
            type: integer
            default: 1
          name: offset
          in: query
        - required: false
          schema:
            title: Limit
            maximum: 1000.0
            minimum: 1.0
            type: integer
            default: 100
          name: limit
          in: query
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Read Attributes Definitions Definitions Attributes Get
                type: array
                items:
                  $ref: "#/components/schemas/AttributeDefinition"
              example:
                - authority: https://opentdf.io
                  name: IntellectualProperty
                  rule: hierarchy
                  state: published
                  order:
                    - TradeSecret
                    - Proprietary
                    - BusinessSensitive
                    - Open
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - OAuth2AuthorizationCodeBearer: []
    put:
      tags:
        - Attributes Definitions
      summary: Update Attribute Definition
      operationId: update_attribute_definition_definitions_attributes_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeDefinition"
            example:
              authority: https://opentdf.io
              name: IntellectualProperty
              rule: hierarchy
              state: published
              order:
                - TradeSecret
                - Proprietary
                - BusinessSensitive
                - Open
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeDefinition"
              example:
                authority: https://opentdf.io
                name: IntellectualProperty
                rule: hierarchy
                state: published
                order:
                  - TradeSecret
                  - Proprietary
                  - BusinessSensitive
                  - Open
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - OAuth2AuthorizationCodeBearer: []
    post:
      tags:
        - Attributes Definitions
      summary: Create Attributes Definitions
      operationId: create_attributes_definitions_definitions_attributes_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeDefinition"
            example:
              authority: https://opentdf.io
              name: IntellectualProperty
              rule: hierarchy
              state: published
              order:
                - TradeSecret
                - Proprietary
                - BusinessSensitive
                - Open
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeDefinition"
              example:
                authority: https://opentdf.io
                name: IntellectualProperty
                rule: hierarchy
                state: published
                order:
                  - TradeSecret
                  - Proprietary
                  - BusinessSensitive
                  - Open
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - OAuth2AuthorizationCodeBearer: []
    delete:
      tags:
        - Attributes Definitions
      summary: Delete Attributes Definitions
      operationId: delete_attributes_definitions_definitions_attributes_delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeDefinition"
            example:
              authority: https://opentdf.io
              name: IntellectualProperty
              rule: hierarchy
              state: published
              order:
                - TradeSecret
                - Proprietary
                - BusinessSensitive
                - Open
        required: true
      responses:
        "202":
          description: No Content
          content:
            application/json:
              schema: {}
              example:
                detail: Item deleted
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - OAuth2AuthorizationCodeBearer: []
  /authorities:
    get:
      tags:
        - Authorities
      summary: Read Authorities
      operationId: read_authorities_authorities_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
              example:
                - https://opentdf.io
      security:
        - OAuth2AuthorizationCodeBearer: []
    post:
      tags:
        - Authorities
      summary: Create Authorities
      operationId: create_authorities_authorities_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthorityDefinition"
            example:
              authority: https://opentdf.io
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
              example:
                - https://opentdf.io
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
      security:
        - OAuth2AuthorizationCodeBearer: []
components:
  schemas:
    AttributeDefinition:
      title: AttributeDefinition
      required:
        - authority
        - name
        - order
        - rule
      type: object
      properties:
        authority:
          title: Authority
          maxLength: 2000
          minLength: 1
          type: string
          format: uri
        name:
          title: Name
          maxLength: 2000
          type: string
        order:
          title: Order
          maxLength: 2000
          type: array
          items:
            maxLength: 2000
            type: string
        rule:
          $ref: "#/components/schemas/RuleEnum"
        state:
          title: State
          maxLength: 64
          type: string
      example:
        authority: https://opentdf.io
        name: IntellectualProperty
        rule: hierarchy
        state: published
        order:
          - TradeSecret
          - Proprietary
          - BusinessSensitive
          - Open
    AuthorityDefinition:
      title: AuthorityDefinition
      required:
        - authority
      type: object
      properties:
        authority:
          title: Authority
          maxLength: 2000
          minLength: 1
          type: string
          format: uri
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    RuleEnum:
      title: RuleEnum
      enum:
        - hierarchy
        - anyOf
        - allOf
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    OAuth2AuthorizationCodeBearer:
      type: oauth2
      flows:
        authorizationCode:
          scopes: {}
          authorizationUrl: ""
          tokenUrl: ""
tags:
  - name: Attributes
    description: "Operations to view data attributes. TDF protocol supports ABAC (Attribute Based Access Control). \n        This allows TDF protocol to implement policy driven and highly scalable access control mechanism."
  - name: Authorities
    description: Operations to view and create attribute authorities.
  - name: Attributes Definitions
    description: "Operations to manage the rules and metadata of attributes. "
